apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform-level components and configurations
  sourceRepos:
    - 'https://github.com/mhuzkhan/aks-gitops-demo'
  destinations:
    - namespace: 'kube-system'
      server: https://kubernetes.default.svc
    - namespace: 'ingress-nginx'
      server: https://kubernetes.default.svc
    - namespace: 'cert-manager'
      server: https://kubernetes.default.svc
    - namespace: 'external-dns'
      server: https://kubernetes.default.svc
    - namespace: 'external-secrets-system'
      server: https://kubernetes.default.svc
    - namespace: 'argocd'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'cert-manager.io'
      kind: ClusterIssuer
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'policy'
      kind: '*'
    - group: 'autoscaling'
      kind: '*'
    - group: 'external-secrets.io'
      kind: '*'
    - group: 'secrets-store.csi.x-k8s.io'
      kind: '*'
  roles:
    - name: platform-admin
      description: Platform administrators
      policies:
        - p, proj:platform:platform-admin, applications, *, platform/*, allow
        - p, proj:platform:platform-admin, repositories, *, *, allow
      groups:
        - argocd-admins
