apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  description: Application workloads
  sourceRepos:
    - 'https://github.com/mhuzkhan/aks-gitops-demo'
  destinations:
    - namespace: 'hello'
      server: https://kubernetes.default.svc
    - namespace: 'default'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'policy'
      kind: '*'
    - group: 'autoscaling'
      kind: '*'
    - group: 'external-secrets.io'
      kind: '*'
    - group: 'secrets-store.csi.x-k8s.io'
      kind: '*'
  roles:
    - name: workload-admin
      description: Workload administrators
      policies:
        - p, proj:workloads:workload-admin, applications, *, workloads/*, allow
      groups:
        - argocd-admins
